In [3]:
import numpy as np

In [ ]:
#1.Represent the data in the given sheet into an appropriate NumPy array so
that you can perform the following actions on it.


In [4]:
temp=np.array([[[[6,23],[14,20],[6,27],[14,22],[8,22],[6,32],[14,29]],[[7,27],[12,29],[11,29],[-13,23],[15,31],[15,30],[8,30]],[[5,21],[12,18],[-1,12],[12,20],[25,27],[17,28],[12,19]],[[-2,15],[0,12],[2,18],[13,24],[10,20],[12,24],[0,17]]],[[[8,23],[14,20],[6,27],[14,22],[8,22],[6,32],[14,29]],[[7,27],[12,29],[11,29],[-13,23],[15,31],[15,30],[8,30]],[[5,21],[12,18],[-1,12],[12,20],[25,27],[17,28],[12,19]],[[-2,15],[0,12],[2,18],[13,24],[10,20],[12,24],[0,17]]],[[[9,23],[14,20],[6,27],[14,22],[8,22],[6,32],[14,29]],[[7,27],[12,29],[11,29],[-13,23],[15,31],[15,30],[8,30]],[[5,21],[12,18],[-1,12],[12,20],[25,27],[17,28],[12,19]],[[-2,15],[0,12],[2,18],[13,24],[10,20],[12,24],[0,17]]],[[[6,23],[14,20],[6,27],[14,22],[8,22],[6,32],[14,29]],[[7,27],[12,29],[11,29],[-13,23],[15,31],[15,30],[8,30]],[[5,21],[12,18],[-1,12],[12,20],[25,27],[17,28],[12,19]],[[-2,15],[0,12],[2,18],[13,24],[10,20],[12,24],[0,17]]]])


In [5]:
print(temp)

[[[[  6  23]
   [ 14  20]
   [  6  27]
   [ 14  22]
   [  8  22]
   [  6  32]
   [ 14  29]]

  [[  7  27]
   [ 12  29]
   [ 11  29]
   [-13  23]
   [ 15  31]
   [ 15  30]
   [  8  30]]

  [[  5  21]
   [ 12  18]
   [ -1  12]
   [ 12  20]
   [ 25  27]
   [ 17  28]
   [ 12  19]]

  [[ -2  15]
   [  0  12]
   [  2  18]
   [ 13  24]
   [ 10  20]
   [ 12  24]
   [  0  17]]]


 [[[  8  23]
   [ 14  20]
   [  6  27]
   [ 14  22]
   [  8  22]
   [  6  32]
   [ 14  29]]

  [[  7  27]
   [ 12  29]
   [ 11  29]
   [-13  23]
   [ 15  31]
   [ 15  30]
   [  8  30]]

  [[  5  21]
   [ 12  18]
   [ -1  12]
   [ 12  20]
   [ 25  27]
   [ 17  28]
   [ 12  19]]

  [[ -2  15]
   [  0  12]
   [  2  18]
   [ 13  24]
   [ 10  20]
   [ 12  24]
   [  0  17]]]


 [[[  9  23]
   [ 14  20]
   [  6  27]
   [ 14  22]
   [  8  22]
   [  6  32]
   [ 14  29]]

  [[  7  27]
   [ 12  29]
   [ 11  29]
   [-13  23]
   [ 15  31]
   [ 15  30]
   [  8  30]]

  [[  5  21]
   [ 12  18]
   [ -1  12]
   [ 12  20]
   [ 25  27]
 

In [ ]:
#2. Write the dimensions and shape of the NumPy array that you have
created.

In [6]:
temp.ndim

4

In [7]:
temp.shape

(4, 4, 7, 2)

In [ ]:
#3. Print the daily temperatures for the first week of each month.

In [13]:
month=['November','December','January','February']
week=['week1','week2','week3','week4']
day=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']

print('Day wise temprature')

for i in range(temp.shape[0]):
    
    j=0
    print(f'\t{month[i]} / Week-1')
    
    for k in range(temp.shape[2]):
        print(f'{day[k]}')
        l=0
        print('Min-',temp[i,j,k,l],chr(176),'C')
        l=l+1
        print('Max-',temp[i,j,k,l],chr(176),'C')
        

Day wise temprature
	November / Week-1
Monday
Min- 6 ° C
Max- 23 ° C
Tuesday
Min- 14 ° C
Max- 20 ° C
Wednesday
Min- 6 ° C
Max- 27 ° C
Thursday
Min- 14 ° C
Max- 22 ° C
Friday
Min- 8 ° C
Max- 22 ° C
Saturday
Min- 6 ° C
Max- 32 ° C
Sunday
Min- 14 ° C
Max- 29 ° C
	December / Week-1
Monday
Min- 8 ° C
Max- 23 ° C
Tuesday
Min- 14 ° C
Max- 20 ° C
Wednesday
Min- 6 ° C
Max- 27 ° C
Thursday
Min- 14 ° C
Max- 22 ° C
Friday
Min- 8 ° C
Max- 22 ° C
Saturday
Min- 6 ° C
Max- 32 ° C
Sunday
Min- 14 ° C
Max- 29 ° C
	January / Week-1
Monday
Min- 9 ° C
Max- 23 ° C
Tuesday
Min- 14 ° C
Max- 20 ° C
Wednesday
Min- 6 ° C
Max- 27 ° C
Thursday
Min- 14 ° C
Max- 22 ° C
Friday
Min- 8 ° C
Max- 22 ° C
Saturday
Min- 6 ° C
Max- 32 ° C
Sunday
Min- 14 ° C
Max- 29 ° C
	February / Week-1
Monday
Min- 6 ° C
Max- 23 ° C
Tuesday
Min- 14 ° C
Max- 20 ° C
Wednesday
Min- 6 ° C
Max- 27 ° C
Thursday
Min- 14 ° C
Max- 22 ° C
Friday
Min- 8 ° C
Max- 22 ° C
Saturday
Min- 6 ° C
Max- 32 ° C
Sunday
Min- 14 ° C
Max- 29 ° C


In [ ]:
#4. Print the temperatures for Tuesday of each month.

In [16]:
month=['November','December','January','February']
week=['week1','week2','week3','week4']
day=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']

for i in range(temp.shape[0]):
    print(f'\t{month[i]}')
    
    for j in range(temp.shape[1]):
        print(f'\t{week[j]} ')
        k=1
        l=0
        print('Min-',temp[i,j,k,l],chr(176),'C')
        l=l+1
        print('Max-',temp[i,j,k,l],chr(176),'C')
        

	November
	week1 
Min- 14 ° C
Max- 20 ° C
	week2 
Min- 12 ° C
Max- 29 ° C
	week3 
Min- 12 ° C
Max- 18 ° C
	week4 
Min- 0 ° C
Max- 12 ° C
	December
	week1 
Min- 14 ° C
Max- 20 ° C
	week2 
Min- 12 ° C
Max- 29 ° C
	week3 
Min- 12 ° C
Max- 18 ° C
	week4 
Min- 0 ° C
Max- 12 ° C
	January
	week1 
Min- 14 ° C
Max- 20 ° C
	week2 
Min- 12 ° C
Max- 29 ° C
	week3 
Min- 12 ° C
Max- 18 ° C
	week4 
Min- 0 ° C
Max- 12 ° C
	February
	week1 
Min- 14 ° C
Max- 20 ° C
	week2 
Min- 12 ° C
Max- 29 ° C
	week3 
Min- 12 ° C
Max- 18 ° C
	week4 
Min- 0 ° C
Max- 12 ° C


In [ ]:
#5. Print only the maximum temperature for all the weekdays of Dec and Feb.

In [18]:
month=['November','December','January','February']
week=['week1','week2','week3','week4']
day=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']

for i in range(1,4,2):
    print(f'\t{month[i]}')
    
    for j in range(temp.shape[1]):
        print(f'\t{week[j]} ')
        for k in range(temp.shape[2]):
            print(f'\t{day[k]} ',temp[i,j,k,l],chr(176),'C')

	December
	week1 
	Monday  23 ° C
	Tuesday  20 ° C
	Wednesday  27 ° C
	Thursday  22 ° C
	Friday  22 ° C
	Saturday  32 ° C
	Sunday  29 ° C
	week2 
	Monday  27 ° C
	Tuesday  29 ° C
	Wednesday  29 ° C
	Thursday  23 ° C
	Friday  31 ° C
	Saturday  30 ° C
	Sunday  30 ° C
	week3 
	Monday  21 ° C
	Tuesday  18 ° C
	Wednesday  12 ° C
	Thursday  20 ° C
	Friday  27 ° C
	Saturday  28 ° C
	Sunday  19 ° C
	week4 
	Monday  15 ° C
	Tuesday  12 ° C
	Wednesday  18 ° C
	Thursday  24 ° C
	Friday  20 ° C
	Saturday  24 ° C
	Sunday  17 ° C
	February
	week1 
	Monday  23 ° C
	Tuesday  20 ° C
	Wednesday  27 ° C
	Thursday  22 ° C
	Friday  22 ° C
	Saturday  32 ° C
	Sunday  29 ° C
	week2 
	Monday  27 ° C
	Tuesday  29 ° C
	Wednesday  29 ° C
	Thursday  23 ° C
	Friday  31 ° C
	Saturday  30 ° C
	Sunday  30 ° C
	week3 
	Monday  21 ° C
	Tuesday  18 ° C
	Wednesday  12 ° C
	Thursday  20 ° C
	Friday  27 ° C
	Saturday  28 ° C
	Sunday  19 ° C
	week4 
	Monday  15 ° C
	Tuesday  12 ° C
	Wednesday  18 ° C
	Thursday  24 ° C
	Frida

In [ ]:
#6. Print all the days along with the week number in November when the
minimum temperature was less than 8 degrees.

In [19]:
month=['November','December','January','February']
week=['week1','week2','week3','week4']
day=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']


    
for j in range(temp.shape[1]):
       
    for k in range(temp.shape[2]):
        if temp[0,j,k,0]<8:
            print(f'week-{j+1} {day[k]} ')

week-1 Monday 
week-1 Wednesday 
week-1 Saturday 
week-2 Monday 
week-2 Thursday 
week-3 Monday 
week-3 Wednesday 
week-4 Monday 
week-4 Tuesday 
week-4 Wednesday 
week-4 Sunday 


In [ ]:
#7. Print all the weeks in Dec and Jan where the maximum temperature has
crossed a threshold of 20 degrees.

In [26]:
month=['November','December','January','February']
week=['week1','week2','week3','week4']
day=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
for i in [1,2]:
    for j in range(0,4):
        if np.any(temp[i,j]>20):
            print(f'{month[i]} week-{j+1}')

December week-1
December week-2
December week-3
December week-4
January week-1
January week-2
January week-3
January week-4


In [ ]:
#8. Check if there are any absurd values present in the dataset(like some temp
which should not be present in the data)

In [22]:
if np.any(temp<0) or np.any(temp>30):
     print('Yes.Absurd value is present.')
else:
    print('No any absurd value.')

Yes.Absurd value is present.


In [ ]:
#10. Find and print the indexes of all the outlier(unusual) values present in
the above dataset.

In [30]:
for i in range(temp.shape[0]):
    
    for j in range(temp.shape[1]): 
        
        for k in range(temp.shape[2]): 
            
            if temp[i,j,k,0]<0:
                print(i,j,k,0)
            
            if temp[i,j,k,1]>50: 
                print(i,j,k,1) 

0 1 3 0
0 2 2 0
0 3 0 0
1 1 3 0
1 2 2 0
1 3 0 0
2 1 3 0
2 2 2 0
2 3 0 0
3 1 3 0
3 2 2 0
3 3 0 0


In [ ]:
#12. Find the average max temperature for the winter months in Jaipur.

In [ ]:
#13. Find the weekly min avg temp for the month of Dec in Jaipur

In [45]:
a=np.mean(temp[1],axis=1)
b=a.reshape(8)
print(np.round(b[0:8:2],2))

[10.    7.86 11.71  5.  ]


In [ ]:
#14. Find the overall avg temp for the months Dec and Jan

In [47]:
print(f'overall avg temp for the month of Dec and Jan :{np.round(np.mean(temp[1:3]),2)}',chr(176),'C')

overall avg temp for the month of Dec and Jan :15.92 ° C


In [ ]:
#15. Find the least temp experienced by the city in the month of Dec and
Jan. Also print the exact date( Day/Week/Month) for the same.

In [50]:
month=['November','December','January','February']
week=['week1','week2','week3','week4']
day=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
for i in range(1,3):
    print(f'least temp in {month[i]} - {np.min(temp[i])}', chr(176),'C')
    min_temp=np.min(temp[1])
    frmt=np.argwhere(temp[i] == min_temp)
    print(f'{day[frmt[0,1]]}/{week[frmt[0,0]]}/{month[i]}')
    

least temp in December - -13 ° C
Thursday/week2/December
least temp in January - -13 ° C
Thursday/week2/January


In [ ]:
#Find the max temp in the month of Feb and return its
date(Day/Week/Month)

In [53]:
print(f'max temp in {month[3]} - {np.max(temp[3])}', chr(176),'C')
max_temp=np.max(temp[3])
frmt=np.argwhere(temp[i] == max_temp)
print(f'{day[frmt[0,1]]}/{week[frmt[0,0]]}/{month[3]}')
    

max temp in February - 32 ° C
Saturday/week1/February


In [ ]:
#17. Find the days in the month of Nov where the max temp of the day
dropped below the avg temp of the month.